openshift/cluster-1.yml: make `auth` required
In https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/65388, I was getting the following when I worked with a file without `auth`:

```
reconcile.utils.gql.GqlApiError: `error` returned with GraphQL response
{
  "message": "Cannot return null for non-nullable field Cluster_v1.auth.",
  "locations": [
    {
      "line": 25,
      "column": 5
    }
  ],
  "path": [
    "clusters",
    40,
    "auth"
  ],
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
````